export const userlist=[
    {
        sno:1,
        name:"kumar",
        phone:'54785478',
        age:20,
        gender:"male"
    },
    {
        sno:2,
        name:"kumar",
        phone:'54785478',
        age:20,
        gender:"male"
    },
    {
        sno:3,
        name:"ravi",
        phone:'54785478',
        age:35,
        gender:"male"
    },
    {
        sno:4,
        name:"pooja",
        phone:'54785478',
        age:24,
        gender:"female"
    },
    {
        sno:5,
        name:"mohit",
        phone:'54785478',
        age:25,
        gender:"male"
    }
];

export const emplist = [
    {
        name:"kumar",
        id:1,
        salary:4500,
        year:2024,
        exp:5,
        projectcount:10
    },
    {
        name:"pankaj",
        id:2,
        salary:4000,
        year:2025,
        exp:4,
        projectcount:8
    },
    {
        name:"mohan",
        id:3,
        salary:5000,
        year:2024,
        exp:9,
        projectcount:12
    },
    {
        name:"pooja",
        id:4,
        salary:6000,
        year:2025,
        exp:10,
        projectcount:15
    }

];
